#! ruby
require 'test/unit'
require 'base_convert'

class TestEntropia < Test::Unit::TestCase
  include BaseConvert
  def test_entropia
    e = Entropia.new bits:64, base:16
    assert_equal 16, e.length
    assert e.to_s.chars.all?{'0123456789ABCDEF'.include? _1}
    e = Entropia.new
    assert_equal 95, e.base
    assert_equal 256.2244, e.bits.round(4)
    assert_equal 39, e.length
    assert_equal 39, e.to_s.length
  end
end
