#! ruby
require 'test/unit'
require 'base_convert'

# Just additional tests beyond original tc_number
# for version 3.1.

class TestInfer < Test::Unit::TestCase
  include BaseConvert

  def test_infer
    # Expect good chance of passing...
    [2,4,8,10,16,32,64,94].each do |base|
      integer = rand(base**64)
      n0 = Number.new(integer, base: base, digits: G94)
      n1 = Number.new n0.to_s
      # check
      assert_equal n0.inspect, n1.inspect
      # reality checks
      assert_equal base, n1.base
      assert_equal n0.to_s, n1.to_s
      assert_equal n0.to_i, n1.to_i
    end

    base, digits = 47, UNAMBIGUOUS
      integer = rand(base**64)
      n0 = Number.new(integer, base: base, digits: digits)
      n1 = Number.new n0.to_s
      # check
      assert_equal n0.inspect, n1.inspect
      # reality checks
      assert_equal base, n1.base
      assert_equal n0.to_s, n1.to_s
      assert_equal n0.to_i, n1.to_i

    base, digits = 64, BASE64
      integer = rand(base**94)
      n0 = Number.new(integer, base: base, digits: digits)
      n1 = Number.new n0.to_s
      # check
      assert_equal n0.inspect, n1.inspect
      # reality checks
      assert_equal base, n1.base
      assert_equal n0.to_s, n1.to_s
      assert_equal n0.to_i, n1.to_i
  end
end
