#! ruby
require 'test/unit'
require 'base_convert'

class A
  include BaseConvert::Methods

  def initialize(integer, string, base, digits)
    @integer,@string,@base,@digits = integer,string,base,digits
  end

  def to_i
    @integer
  end

  def to_s
    @string
  end
end

class TestMethods < Test::Unit::TestCase
  def test_toi
    assert_nil BaseConvert::Methods.toi('', 2, '01')
    assert_equal 0, BaseConvert::Methods.toi('_____', 4, '_123')
    assert_equal 2, BaseConvert::Methods.toi('___1_', 2, '_123')
    assert_equal 18, BaseConvert::Methods.toi('1__1_', 2, '_123')
  end

  def test_tos
    assert_equal '', BaseConvert::Methods.tos(nil, 16, '0123456789abcdef')
    assert_equal 'X', BaseConvert::Methods.tos(0, 16, 'X123456789abcdef')
    assert_equal '...', BaseConvert::Methods.tos(4095, 16, '0123456789abcde.')
  end

  def test_chars_ordered
    assert BaseConvert::Methods.chars_ordered? '123'
    assert BaseConvert::Methods.chars_ordered? 'AZaz'
    refute BaseConvert::Methods.chars_ordered? '1203'
    refute BaseConvert::Methods.chars_ordered? 'azAZ'
  end

  def test_base_convert_mixin
    a = A.new(123, '321', 10, '0123456789')
    assert_equal 321, a.toi
    assert_equal '123', a.tos
    assert a.chars_ordered?

    a = A.new(255, 'AA', 16, '0123456789ABCDEFzyx')
    assert_equal 170, a.toi
    assert_equal 'FF', a.tos
    refute a.chars_ordered? # ordered would be '0123456789ABCDEFxyz'
  end
end
