#! ruby
require 'test/unit'
require 'base_convert'
require 'digest'

class TestOriginal < Test::Unit::TestCase
  include BaseConvert

  def test_001_to_s_n
    # test against number.to_s(n)
    2.upto(36) do |n|
      # Converts to base n.
      base = FromTo.new(n)
      100.times do
        number = rand(10000)
        string = number.to_s(n)
        # FromTo uses caps
        assert_equal(string.upcase, base.integer2base(number))
        # and it will automatically upcase
        assert_equal(number, base.base2integer(string))
      end
    end
  end

  def test_002_hello_world
    hexdigest = Digest::SHA256.hexdigest('Hello World!') # and verified below
    assert_equal '7f83b1657ff1fc53b92dc18148a1d65dfc2d4b1fa3d677284addd200126d9069', hexdigest

    word = FromTo.new(:hex, :word).convert(hexdigest)
    assert_equal 'UEjKBW7lvEq1KjyCxAYQRJqmvffQEbwLNvzs8Ggdy4P', word

    assert_equal hexdigest.upcase, FromTo.new(:word, :hex).convert(word)

    qstring = '$<c6PCX_mugC58xfO5JOp+V4|<jHekI^_WE$?d?9'
    assert_equal qstring, FromTo.new(:hex, :qgraph).convert(hexdigest)
    assert_equal hexdigest.upcase, FromTo.new(:qgraph, :hex).convert(qstring)
  end

  def test_003_hundred_million
    assert_equal '6laZE', FromTo.new(10, 62).convert( 100_000_000 )
    assert_equal ')8]3H', FromTo.new(63).integer2base( 100_000_000 )

    base = FromTo.new(62)
    base.to_digits = FromTo::QGRAPH
    assert_equal ')RGF1', base.integer2base( 100_000_000 )
  end

end
