#! ruby
require 'test/unit'

class TestVersion < Test::Unit::TestCase
  def test_version
    lib_version = `egrep -o '[0-9]+\\.[0-9]+\\.[0-9]+' lib/*.rb`.split.first
    gemspec_version = `egrep -o '[0-9]+\\.[0-9]+\\.[0-9]+' *.gemspec`.split.first
    assert_match /^\d+\.\d+\.\d+$/, lib_version
    assert_equal lib_version, gemspec_version
  end
end
