#! ruby
require 'test/unit'

class TestVersion < Test::Unit::TestCase
  def test_version
    version = '4.0.200109'
    assert_equal(version, `egrep -o '[0-9]+\\.[0-9]+\\.[0-9]+' lib/*.rb`.split.first)
    if File.exist?('data/VERSION')
      assert_equal(version, File.read('data/VERSION').strip)
    end
    if executable = `ls bin/*`.split.first
      assert_equal(version, `#{executable} --version`.strip)
    end
    if gemspec = `ls *.gemspec`.split.first
      assert_equal(version, `egrep -o '[0-9]+\\.[0-9]+\\.[0-9]+' #{gemspec}`.split.first)
    end
  end
end
